### ISSUE TITLE
Feature Request: Add Custom Information to Header

### ISSUE THREAD

**Issue by ASRagab** [ahmadnassri/action-terraform-report#57]
Would it be possible to have some additional context such that we could add some custom information to the Report Header specifically 

🤖 Terraform Report <- custom information here ->

We run our terraform for different environments/regions it would be nice to have the region/env information right at the top?

I would be willing to submit a PR, if you think that feature is acceptable.

**Comment by ahmadnassri** [comment]
sure, let's see the PR

**Comment by ASRagab** [comment]
@ahmadnassri please take a look, when you have a moment.

**Comment by ahmadnassri** [comment]
this is now released in https://github.com/ahmadnassri/action-terraform-report/releases/tag/v3.2.0

**Comment by ASRagab** [comment]
I am sorry to hear, @ahmadnassri! Thank you!
