### ISSUE TITLE
Cant handle large deltas - >= 65k

### ISSUE THREAD

**Issue by thomas-edt** [ahmadnassri/action-terraform-report#68]
There is a limit on the github api where if the terraform delta is over 65k chars, that the Github api cant handle the comment request. 

It would be amazing if this action could trim the plan to be within the limiit and indicate in the comment that its been truncated.

**Comment by ahmadnassri** [comment]
there are definitely limits!

do you have `show-diff` set to `true`?

**Comment by thomas-edt** [comment]
no, just the default

**Comment by marcossv9** [comment]
Hi folks, I'm also getting the same error, is there any workaround in the meantime?
Thanks!

**Comment by ahmadnassri** [comment]
this is now resolved with v4.1.0
